// AUTOMATICALLY GENERATED GRAPH DESCRIPTION
document.title = "Chapel Performance Graphs for sven0";
var pageTitle = "Chapel Performance Graphs for sven0";
var runDate= "2026-05-21";
var numericX = false;
var configurations = [];
var configurationsVis = [];
var allGraphs = [
{
   "title" : "Global STREAM Time",
   "suites" : ["Release examples"],
   "datfname" : "stream0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC STREAM-EP Time",
   "suites" : ["Release examples"],
   "datfname" : "stream-ep0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LULESH (release)",
   "suites" : ["Release examples", "Performance tracking"],
   "datfname" : "lulesh0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC RA Time",
   "suites" : ["Release examples", "Performance tracking"],
   "datfname" : "ra0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "BigInteger Performance (fast ops)",
   "suites" : ["Performance tracking"],
   "datfname" : "bigintops0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "BigInteger Performance (slow ops)",
   "suites" : ["Performance tracking"],
   "datfname" : "bigintops1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Associative Type Add/Remove",
   "suites" : ["Performance tracking"],
   "datfname" : "primes0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "1D ArrayView Parallel Indexing",
   "suites" : ["Performance tracking"],
   "datfname" : "views-forall-index0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "1D ArrayView Parallel Iteration",
   "suites" : ["Performance tracking"],
   "datfname" : "views-forall-iter0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Array View Creation",
   "suites" : ["Performance tracking"],
   "datfname" : "create-views0.json",
   "ylabel" : "Rate (Mviews/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "List Operations",
   "suites" : ["Performance tracking"],
   "datfname" : "listBenchmark10.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "One Billion Row Challenge (using 10 million row input set)",
   "suites" : ["Performance tracking"],
   "datfname" : "1brc0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Sin LUT single locale",
   "suites" : ["Performance tracking"],
   "datfname" : "sinlut0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Dot Product Vectorization with real(64)",
   "suites" : ["Performance tracking"],
   "datfname" : "dotProduct-real640.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Dot Product Vectorization with int(32)",
   "suites" : ["Performance tracking"],
   "datfname" : "dotProduct-int320.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Dot Product Vectorization with real(64) with large arrays",
   "suites" : ["Performance tracking"],
   "datfname" : "dotProduct-real64-big0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Clenshaw",
   "suites" : ["Performance tracking"],
   "datfname" : "clenshaw0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Loop Division Scalar Kernel",
   "suites" : ["Performance tracking"],
   "datfname" : "loopDivision0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "conditional mask vectorization",
   "suites" : ["Performance tracking"],
   "datfname" : "ifMask0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Global STREAM",
   "suites" : ["Performance tracking", "HPC Challenge"],
   "datfname" : "STREAM_study0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Global STREAM using Promotion",
   "suites" : ["HPC Challenge"],
   "datfname" : "STREAM_study_promote0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC FFT Time",
   "suites" : ["HPC Challenge"],
   "datfname" : "fft0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC PTRANS Time (numrows=5733)",
   "suites" : ["HPC Challenge"],
   "datfname" : "ptrans0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LSU 1D heat diffusion codes (n=10,000,000)",
   "suites" : ["HPC Challenge"],
   "datfname" : "heat0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Global STREAM Performance (GB/s)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "stream_performance0.json",
   "ylabel" : "Performance (GB/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC RA Performance (GUPS)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "ra_performance0.json",
   "ylabel" : "Performance (GUPS)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC STREAM-EP Performance (GB/s)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "stream-ep_performance0.json",
   "ylabel" : "Performance (GB/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "EP STREAM (fragmented) (GB/s)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "STREAM_study_performance0.json",
   "ylabel" : "Performance (GB/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Global STREAM (GB/s)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "STREAM_study_performance1.json",
   "ylabel" : "Performance (GB/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Global STREAM using Promotion (GB/s)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "STREAM_study_performance2.json",
   "ylabel" : "Performance (GB/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC FFT Performance (Gflop/s)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "fft_performance0.json",
   "ylabel" : "Performance (Gflop/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC HPL Performance (Gflop/s)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "hpl_performance0.json",
   "ylabel" : "Performance (Gflop/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC PTRANS Performance (GB/sec) (nrows=5733)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "ptrans_performance0.json",
   "ylabel" : "Performance (GB/sec)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "SSCA#2 Kernel 4 TEPS (SCALE=8)",
   "suites" : ["Performance Graphs (TEPS, GB/s, etc.)"],
   "datfname" : "performance0.json",
   "ylabel" : "Performance (TEPS)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "SSCA#2 Kernels 2 & 3 (SCALE=8)",
   "suites" : ["Proxy apps"],
   "datfname" : "SSCA2_main0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "SSCA#2 Kernel 4 (SCALE=8)",
   "suites" : ["Proxy apps"],
   "datfname" : "SSCA2_main1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "SSCA#2 Graph Construction (SCALE=8)",
   "suites" : ["Proxy apps"],
   "datfname" : "edge_generation0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "SSCA#2 (SCALE=8)",
   "suites" : ["Proxy apps"],
   "datfname" : "total_time0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LULESH (bradc study version)",
   "suites" : ["Proxy apps"],
   "datfname" : "lulesh-dense0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "miniMD LJ (--size=10) Time",
   "suites" : ["Performance tracking", "Proxy apps"],
   "datfname" : "miniMD0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LLNL CoMD Time (sec)",
   "suites" : ["Performance tracking", "Proxy apps"],
   "datfname" : "CoMD0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Elegant AoS CoMD Time (sec)",
   "suites" : ["Performance tracking", "Proxy apps"],
   "datfname" : "CoMD-elegant-aos0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LCALS (raw, short)",
   "suites" : ["Proxy apps"],
   "datfname" : "LCALS-raw-short0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LCALS (raw, medium)",
   "suites" : ["Proxy apps"],
   "datfname" : "LCALS-raw-medium0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LCALS (raw, long)",
   "suites" : ["Proxy apps"],
   "datfname" : "LCALS-raw-long0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LCALS (raw_omp, short)",
   "suites" : ["Proxy apps"],
   "datfname" : "LCALS-parallel-short0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LCALS (raw_omp, medium)",
   "suites" : ["Proxy apps"],
   "datfname" : "LCALS-parallel-medium0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LCALS (raw_omp, long)",
   "suites" : ["Proxy apps"],
   "datfname" : "LCALS-parallel-long0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LCALS (raw_vector_only, short)",
   "suites" : ["Proxy apps"],
   "datfname" : "LCALS-raw-vector-only-short0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LCALS (raw_vector_only, medium)",
   "suites" : ["Proxy apps"],
   "datfname" : "LCALS-raw-vector-only-medium0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LCALS (raw_vector_only, long)",
   "suites" : ["Proxy apps"],
   "datfname" : "LCALS-raw-vector-only-long0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Binary Trees Shootout Benchmark (n=21)",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "binary-trees0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Chameneos Redux Shootout Benchmark (n=6,000,000)",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "chameneos-redux0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Fasta Shootout Benchmark (n=25,000,000)",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "fasta0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-20",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "K-nucleotide Shootout Benchmark",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "knucleotide0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Meteor Shootout Benchmark (n=2098)",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "meteor0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "N-body variations",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "nbody0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Pi digits variations",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "pidigits0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Regex-dna Shootout Benchmark",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "regexdna0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Regex-dna redux Shootout Benchmark",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "regexdna-redux0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Reverse-complement Shootout Benchmark",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "revcomp0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Thread Ring Shootout Benchmark (n=50,000,000)",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks"],
   "datfname" : "thread-ring0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted Binary Trees Shootout Benchmark (n=21)",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "binarytrees-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted Fannkuch-Redux Shootout Benchmark (n=12)",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "fannkuchredux-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted Fasta Shootout Benchmark",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "fasta-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted K-nucleotide Shootout Benchmark",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "knucleotide-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted Mandelbrot Shootout Benchmark",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "mandelbrot-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted N-body Shootout Benchmark",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "nbody-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted Pi digits Shootout Benchmark",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "pidigits-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted Regex-dna Shootout Benchmark",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "regexdna-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted Regex-dna redux Shootout Benchmark",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "regexdnaredux-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted Reverse-complement Shootout Benchmark",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "revcomp-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Submitted Spectral Norm Shootout Benchmark",
   "suites" : ["Submitted Shootout benchmarks"],
   "datfname" : "spectralnorm-submitted0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Fasta Shootout Benchmark (historical)",
   "suites" : ["Shootout extras"],
   "datfname" : "fasta-extras0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-20",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Fasta-redux Shootout Benchmark (n=25,000,000)",
   "suites" : ["Shootout extras"],
   "datfname" : "fastaredux0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-20",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Mandelbrot all",
   "suites" : ["Shootout extras"],
   "datfname" : "mandelbrot-extras0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-20",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Spectral Norm Step Size Times",
   "suites" : ["Shootout extras"],
   "datfname" : "spectral-norm-specify-step0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Parboil BFS Execution Time",
   "suites" : ["Parboil benchmarks"],
   "datfname" : "bfs0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Parboil Histo Serial Execution Time",
   "suites" : ["Parboil benchmarks"],
   "datfname" : "histo0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Parboil SAD Serial Execution Time",
   "suites" : ["Parboil benchmarks"],
   "datfname" : "sad0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Parboil Stencil 3D Execution Time",
   "suites" : ["Parboil benchmarks"],
   "datfname" : "stencil0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Black-Scholes (PARSEC benchmark)",
   "suites" : ["PARSEC benchmarks"],
   "datfname" : "blackscholes0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Black-Scholes (PARSEC benchmark) using Promotion",
   "suites" : ["PARSEC benchmarks"],
   "datfname" : "blackscholes_promote0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "ISx variations",
   "suites" : ["Performance tracking", "ISx benchmark"],
   "datfname" : "isx0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "ISx (SPMD over Buckets)",
   "suites" : ["ISx benchmark"],
   "datfname" : "isx-bucket-spmd0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "ISx (Hand Optimized)",
   "suites" : ["ISx benchmark"],
   "datfname" : "isx-hand-optimized0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "ISx (Avoids array returns)",
   "suites" : ["ISx benchmark"],
   "datfname" : "isx-no-return0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "ISx (Pure SPMD)",
   "suites" : ["ISx benchmark"],
   "datfname" : "isx-per-task0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "ISx (Release)",
   "suites" : ["Performance tracking", "ISx benchmark"],
   "datfname" : "isx-release0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "PRK synch_p2p",
   "suites" : ["PRK benchmarks"],
   "datfname" : "prk-synch_p2p0.json",
   "ylabel" : "Rate (MFlops/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "PRK synch_p2p time",
   "suites" : ["PRK benchmarks"],
   "datfname" : "prk-synch_p2p-time0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "PRK stencil",
   "suites" : ["PRK benchmarks"],
   "datfname" : "prk-stencil0.json",
   "ylabel" : "Rate (MFlops/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "PRK stencil time",
   "suites" : ["Performance tracking", "PRK benchmarks"],
   "datfname" : "prk-stencil-time0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "PRK transpose",
   "suites" : ["PRK benchmarks"],
   "datfname" : "prk-transpose0.json",
   "ylabel" : "Rate (MB/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "PRK transpose time",
   "suites" : ["PRK benchmarks"],
   "datfname" : "prk-transpose-time0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: CG timings - size S",
   "suites" : ["NAS Parallel benchmarks"],
   "datfname" : "cg0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: CG timings - size W",
   "suites" : ["NAS Parallel benchmarks"],
   "datfname" : "cg1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: CG timings - size A",
   "suites" : ["Performance tracking", "NAS Parallel benchmarks"],
   "datfname" : "cg-a0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: FT timings - size S",
   "suites" : ["NAS Parallel benchmarks"],
   "datfname" : "ft0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: FT timings - size W",
   "suites" : ["NAS Parallel benchmarks"],
   "datfname" : "ft1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: FT timings - size A",
   "suites" : ["Performance tracking", "NAS Parallel benchmarks"],
   "datfname" : "ft-a0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NPB MG Size S",
   "suites" : ["NAS Parallel benchmarks"],
   "datfname" : "mg0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NPB MG Size A",
   "suites" : ["NAS Parallel benchmarks"],
   "datfname" : "mg1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NPB MG Size B",
   "suites" : ["Performance tracking", "NAS Parallel benchmarks"],
   "datfname" : "mg-b0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Scalar Multiplication 2D Array Execution Time",
   "suites" : ["Array/Domain performance"],
   "datfname" : "arrayPerformance-2d0.json",
   "ylabel" : "Time (milliseconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Serial 1D Array Performance",
   "suites" : ["Array/Domain performance"],
   "datfname" : "arrayPerformance-1d0.json",
   "ylabel" : "Time (milliseconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "array vs tuple serial accesses",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "time_array_vs_tuple0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "array vs ddata serial accesses",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "time_array_vs_ddata0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Serial Array Access vs. Reference Access",
   "suites" : ["Array/Domain performance"],
   "datfname" : "time_array_vs_ref0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Array Access vs. Reference Access in forall loop",
   "suites" : ["Array/Domain performance"],
   "datfname" : "time_array_vs_ref_forall0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Serial Array Access vs. Reference Access (Multidimensional)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "time_array_vs_ref_multidim0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "1D Domain vs. Range Parallel Iteration",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "forall-dom-range0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "1D Array Parallel Iteration",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "arr-forall0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Promoted op= Time (local)",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "parOpEquals0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Promoted op= Time (no-local)",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "parOpEquals1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Array copy from Global to Local (Cyclic)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "copy_to_local0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "2D Array Assignment (256x256)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "assign.2560.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "DGEMM Performance (128x128)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "dgemm.1280.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "2D Array Assignment (1024x1024, faster idioms)",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "assign.10240.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "2D Array Assignment (1024x1024, slower idioms)",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "assign.10241.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "2D non-local Array Non-local Assignment (256x256)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "assign_across_locales.2560.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "DGEMM Performance (64x64)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "dgemm.640.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "2D non-local Array Assignment (1024x1024)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "assign_across_locales.10240.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Array initialization (faster idioms)",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "init0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Array initialization (slower idioms)",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "init1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Associative Array Iteration",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "array_iter0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Associative Domain Iteration",
   "suites" : ["Array/Domain performance"],
   "datfname" : "domain_iter0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Identical domain equality Timings (sec)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "domEqualityPerf0.json",
   "ylabel" : "Time (sec)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "2D Matrix Multiply",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "matrix-multiply0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Array of string element access",
   "suites" : ["Array/Domain performance"],
   "datfname" : "array-of-strings-read0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "array return performance, serial/parallel, 8 element array",
   "suites" : ["Array/Domain performance"],
   "datfname" : "return-array-80.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "array return performance, serial/parallel, 20000000 element array",
   "suites" : ["Array/Domain performance"],
   "datfname" : "return-array-200000000.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "array return performance, serial/parallel, 40000000 element array",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "return-array-400000000.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Building up associative domains",
   "suites" : ["Performance tracking", "Array/Domain performance"],
   "datfname" : "build-associative0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Sparse Domain Assignment (similar layouts, ~5M indices)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "domainAssignment-similar0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Sparse Domain Assignment (dissimilar layouts, ~50K indices)",
   "suites" : ["Array/Domain performance"],
   "datfname" : "domainAssignment-dissimilar0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Array init/deinit performance, 40000000 element array",
   "suites" : ["Array/Domain performance"],
   "datfname" : "arrayInitDeinitPerf0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Parallel Atomic fetchAdd Time (sec)",
   "suites" : ["Performance tracking", "Atomic performance"],
   "datfname" : "atomictest0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Dynamic Iterator",
   "suites" : ["Dynamic iterators"],
   "datfname" : "dynamic0.json",
   "ylabel" : "Time (millisec.)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Adaptative WS v1 Iterator (BS, BS)",
   "suites" : ["Dynamic iterators"],
   "datfname" : "distAdaptativeWSv10.json",
   "ylabel" : "Time (millisec.)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Adaptative WS v2 Iterator (BS, BS)",
   "suites" : ["Dynamic iterators"],
   "datfname" : "distAdaptativeWSv20.json",
   "ylabel" : "Time (millisec.)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Guided Iterator",
   "suites" : ["Dynamic iterators"],
   "datfname" : "guided0.json",
   "ylabel" : "Time (millisec.)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Adaptative WS Iterator (BS, BS)",
   "suites" : ["Dynamic iterators"],
   "datfname" : "distAdaptativeWS0.json",
   "ylabel" : "Time (millisec.)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "For+Begin Timings",
   "suites" : ["Parallel Statement Comparisons"],
   "datfname" : "forBeginCompare0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Coforall Timings",
   "suites" : ["Parallel Statement Comparisons"],
   "datfname" : "coforallCompare0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Coforall+Begin Timings",
   "suites" : ["Parallel Statement Comparisons"],
   "datfname" : "coforallBeginCompare0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Early Exit Task Parallel Timings",
   "suites" : ["Parallel Statement Comparisons"],
   "datfname" : "loopCompare0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Task Parallel Timings",
   "suites" : ["Parallel Statement Comparisons"],
   "datfname" : "loopCompare1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Empty Task Spawn Timings (500,000 x maxTaskPar)",
   "suites" : ["Task Spawning"],
   "datfname" : "taskSpawn0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Empty Serialized Task Spawn Timings (500,000 x maxTaskPar)",
   "suites" : ["Task Spawning"],
   "datfname" : "serialTaskSpawn0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Task Yield Timings (500,000 yields/task)",
   "suites" : ["Task Spawning"],
   "datfname" : "taskYield0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Task Placement STREAM Performance (GB/s)",
   "suites" : ["Task Spawning"],
   "datfname" : "stream-task-placement0.json",
   "ylabel" : "Performance (GB/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Empty Barrier Timings (500,000 x maxTaskPar)",
   "suites" : ["Barrier"],
   "datfname" : "empty-chpl-barrier0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "SPMD Barrier STREAM Performance (GB/s)",
   "suites" : ["Barrier"],
   "datfname" : "stream-spmd-barrier0.json",
   "ylabel" : "Performance (GB/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Memory Usage for examples Tests",
   "suites" : ["Memory tracking"],
   "datfname" : "memleaks0.json",
   "ylabel" : "bytes",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Memory Leaks for examples Tests",
   "suites" : ["Memory tracking"],
   "datfname" : "memleaks1.json",
   "ylabel" : "bytes",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Number of Tests with Leaks (examples only)",
   "suites" : ["Memory tracking"],
   "datfname" : "memleaks2.json",
   "ylabel" : "# tests",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Memory Usage for all Tests",
   "suites" : ["Memory tracking"],
   "datfname" : "memleaksfull0.json",
   "ylabel" : "bytes",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Memory Leaks for all Tests",
   "suites" : ["Memory tracking"],
   "datfname" : "memleaksfull1.json",
   "ylabel" : "bytes",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Number of Tests with Leaks",
   "suites" : ["Memory tracking"],
   "datfname" : "memleaksfull2.json",
   "ylabel" : "# tests",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Memory Usage for Multilocale Tests",
   "suites" : ["Memory tracking"],
   "datfname" : "ml-memleaksfull0.json",
   "ylabel" : "bytes",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Memory Leaks for Multilocale Tests",
   "suites" : ["Memory tracking"],
   "datfname" : "ml-memleaksfull1.json",
   "ylabel" : "bytes",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Number of Multilocale Tests with Leaks",
   "suites" : ["Memory tracking"],
   "datfname" : "ml-memleaksfull2.json",
   "ylabel" : "# tests",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Serial 'object' Allocation",
   "suites" : ["Memory allocation"],
   "datfname" : "allocation0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Jacobi AST size",
   "suites" : ["Performance tracking", "Code size tracking"],
   "datfname" : "jacobi0.json",
   "ylabel" : "size (KB)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Jacobi Emitted Code Size",
   "suites" : ["Performance tracking", "Code size tracking"],
   "datfname" : "jacobi1.json",
   "ylabel" : "statements",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "no-op (non-user code startup time)",
   "suites" : ["Performance tracking", "Startup tracking"],
   "datfname" : "no-op0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: EP timings - size S",
   "suites" : ["NAS Parallel benchmarks", "MAX_LOGICAL comparison"],
   "datfname" : "ep0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: EP timings - size W",
   "suites" : ["NAS Parallel benchmarks", "MAX_LOGICAL comparison"],
   "datfname" : "ep1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: EP timings - size A",
   "suites" : ["NAS Parallel benchmarks", "MAX_LOGICAL comparison"],
   "datfname" : "ep2.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "NAS Parallel Benchmarks: EP timings - size B",
   "suites" : ["Performance tracking", "NAS Parallel benchmarks", "MAX_LOGICAL comparison"],
   "datfname" : "ep-b0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "HPCC HPL Time",
   "suites" : ["HPC Challenge", "MAX_LOGICAL comparison"],
   "datfname" : "hpl0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "EP STREAM (fragmented)",
   "suites" : ["Performance tracking", "HPC Challenge", "MAX_LOGICAL comparison"],
   "datfname" : "STREAM_study_fragmented0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Fannkuch-Redux (n=12)",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks", "MAX_LOGICAL comparison"],
   "datfname" : "fannkuch-redux0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Spectral Norm Shootout Benchmark",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks", "MAX_LOGICAL comparison"],
   "datfname" : "spectralnorm0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Mandelbrot variations",
   "suites" : ["Release examples", "Performance tracking", "Shootout benchmarks", "MAX_LOGICAL comparison"],
   "datfname" : "mandelbrot0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-20",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "cast from string time by dest type",
   "suites" : ["String perf tests"],
   "datfname" : "cast-from-string0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "String temporary copies",
   "suites" : ["Performance tracking", "String perf tests"],
   "datfname" : "temporary-copies0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Splitting a string on whitespace",
   "suites" : ["String perf tests"],
   "datfname" : "split-whitespace-perf0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Allocating string operations",
   "suites" : ["String perf tests"],
   "datfname" : "allocate0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Passing and returning strings",
   "suites" : ["Performance tracking", "String perf tests"],
   "datfname" : "arguments0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Searches over n strings (historical)",
   "suites" : ["Performance tracking", "String perf tests"],
   "datfname" : "search0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Searches over n strings",
   "suites" : ["String perf tests"],
   "datfname" : "search-throughput0.json",
   "ylabel" : "Throughput (MB/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Search within a string",
   "suites" : ["String perf tests"],
   "datfname" : "substring0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Linearithmic sorts on 2^24 bytes of shuffled data",
   "suites" : ["Standard Library"],
   "datfname" : "sorts-linearithmic0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Quadratic sorts on 2^12 bytes of shuffled data",
   "suites" : ["Standard Library"],
   "datfname" : "sorts-quadratic0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LinearAlgebra.dot() performance (2048*2048 matrix)",
   "suites" : ["Standard Library"],
   "datfname" : "dot-perf0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Transpose 10x10",
   "suites" : ["Standard Library"],
   "datfname" : "linearalgebra-perf0.json",
   "ylabel" : "Time",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Transpose 1000x1000",
   "suites" : ["Standard Library"],
   "datfname" : "linearalgebra-perf1.json",
   "ylabel" : "Time",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LU factorization - 1000x1000",
   "suites" : ["Standard Library"],
   "datfname" : "linearalgebra-perf2.json",
   "ylabel" : "Time",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Sparse matrix-matrix multiplication variations - big (N = 10e7)",
   "suites" : ["Standard Library"],
   "datfname" : "linearalgebra-perf3.json",
   "ylabel" : "Time",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Sparse matrix-matrix multiplication variations - small (N = 10e3)",
   "suites" : ["Standard Library"],
   "datfname" : "linearalgebra-perf4.json",
   "ylabel" : "Time",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LinearAlgebra.Sparse.dot() - squaring NxN matrices - big (N = 10e7)",
   "suites" : ["Standard Library"],
   "datfname" : "linearalgebra-perf5.json",
   "ylabel" : "Time",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "LinearAlgebra.Sparse.dot() - squaring NxN matrices - small (N = 10e3)",
   "suites" : ["Standard Library"],
   "datfname" : "linearalgebra-perf6.json",
   "ylabel" : "Time",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Jacobi method - solving 512 unknowns - dense and sparse",
   "suites" : ["Standard Library"],
   "datfname" : "linearalgebra-perf7.json",
   "ylabel" : "Time",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "CSR-CSC multiplication",
   "suites" : ["Standard Library"],
   "datfname" : "cs-multiplication0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "CSDom._grow()",
   "suites" : ["Standard Library"],
   "datfname" : "cs-resize0.json",
   "ylabel" : "Time (ms)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "CSDom._bulkGrow()",
   "suites" : ["Standard Library"],
   "datfname" : "cs-resize1.json",
   "ylabel" : "Time (ms)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Radix sorts on 2^24 bytes of shuffled data",
   "suites" : ["Standard Library"],
   "datfname" : "radixsortMSB0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Spiral 5.0 Chapel FFT example",
   "suites" : ["Performance tracking", "Misc"],
   "datfname" : "main0.json",
   "ylabel" : "Time (us)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Serial Reduction Styles",
   "suites" : ["Performance tracking", "Misc"],
   "datfname" : "testSerialReductions0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Reductions Time (sec)",
   "suites" : ["Performance tracking", "Misc"],
   "datfname" : "reductions-perf0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Forall with AoA In and Reduce Intents",
   "suites" : ["Misc"],
   "datfname" : "ri-a2-AoA0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "PARACR Block to Cyclic redistribution",
   "suites" : ["Misc"],
   "datfname" : "PARACR-BC0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "BitOps - popcount - C",
   "suites" : ["Misc"],
   "datfname" : "bitops0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "BitOps - clz - C",
   "suites" : ["Misc"],
   "datfname" : "bitops1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "BitOps - ctz - C",
   "suites" : ["Misc"],
   "datfname" : "bitops2.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "randomStream.next (50M trials)",
   "suites" : ["Misc"],
   "datfname" : "nextPerf0.json",
   "ylabel" : "Time(seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "RBC benchmark",
   "suites" : ["Performance tracking", "Misc"],
   "datfname" : "RBC0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "C-Ray Tracer",
   "suites" : ["Performance tracking", "Misc"],
   "datfname" : "c-ray0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "1D scan time",
   "suites" : ["Misc"],
   "datfname" : "scanPerf0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Repeated Large Binary IO (n=10000)",
   "suites" : ["Misc"],
   "datfname" : "large_binary_io0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Performance of Various Jacobi1D Implementations",
   "suites" : ["Colorado State University"],
   "datfname" : "Jacobi1D0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Performance of Various Jacobi2D Implementations",
   "suites" : ["Colorado State University"],
   "datfname" : "Jacobi2D0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Performance of Various CFD-mini Implementations",
   "suites" : ["Colorado State University"],
   "datfname" : "cfd-mini0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Training Time of Multiple CNNs With Different Architectures and Hyperparameters",
   "suites" : ["ML"],
   "datfname" : "mnist_cnn0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Training Time of XOR Perceptron",
   "suites" : ["ML"],
   "datfname" : "xor_mlp0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Time to build trees",
   "suites" : ["Performance tracking", "Nikhil Padmanabhan"],
   "datfname" : "twopt-buildtrees0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Time to tree paircount",
   "suites" : ["Performance tracking", "Nikhil Padmanabhan"],
   "datfname" : "twopt-paircount0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Elegance arrayAdd",
   "suites" : ["Elegance"],
   "datfname" : "elegance0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Elegance promotedOp",
   "suites" : ["Elegance"],
   "datfname" : "elegance1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Elegance tuplesVSarrays",
   "suites" : ["Elegance"],
   "datfname" : "elegance2.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Bale: Toposort Perf (Rows/s)",
   "suites" : ["Bale"],
   "datfname" : "toposort.perf0.json",
   "ylabel" : "Performance (Rows/s)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Bale: Toposort Time (seconds)",
   "suites" : ["Bale"],
   "datfname" : "toposort.time0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Storing Words in Moby Dick into a Map",
   "suites" : ["Serial Performance"],
   "datfname" : "moby-perf0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Performance of primality test",
   "suites" : ["Serial Performance", "- Chapel versus C Comparisons"],
   "datfname" : "prime0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "For Loop Time Compare",
   "suites" : ["Serial Performance", "- Chapel versus C Comparisons"],
   "datfname" : "forCompare0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "While Loop Time Compare",
   "suites" : ["Serial Performance", "- Chapel versus C Comparisons"],
   "datfname" : "whileCompare0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "c vs chpl writing single newlines to stdout",
   "suites" : ["Serial Performance", "- Chapel versus C Comparisons"],
   "datfname" : "time-write0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "c vs chpl serial accesses",
   "suites" : ["Performance tracking", "Array/Domain performance", "Serial Performance", "- Chapel versus C Comparisons"],
   "datfname" : "time_iterate0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "c vs chpl multidimensional and array of arrays serial accesses",
   "suites" : ["Performance tracking", "Array/Domain performance", "Serial Performance", "- Chapel versus C Comparisons"],
   "datfname" : "time_access0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Extern Method Call Time Compare",
   "suites" : ["Serial Performance", "- Chapel versus C Comparisons"],
   "datfname" : "externMethodCallPerf0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Loop Time Compare",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "forVersusWhilePerf0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Conditional Statement Compare (Balanced)",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "ifVersusSelect0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Conditional Statement Compare (random)",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "ifVersusSelect.random0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Conditional Statement Compare (Reversed)",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "ifVersusSelect.alternates0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Conditional Statement Compare (SkewedLow)",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "ifVersusSelect.alternates1.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Conditional Statement Compare (SkewedMid)",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "ifVersusSelect.alternates2.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Conditional Statement Compare (SkewedHigh)",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "ifVersusSelect.alternates3.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Module versus Method variable access",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "moduleVersusFunctionBaseline0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Module versus Method multiplication/division",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "moduleVersusFunctionDifAccess0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Module versus Method mod comparison",
   "suites" : ["Serial Performance", "- Statement Comparisons"],
   "datfname" : "moduleVersusFunction0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "plb2 matmul",
   "suites" : ["plb2 benchmarks"],
   "datfname" : "matmul0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "plb2 nqueen",
   "suites" : ["plb2 benchmarks"],
   "datfname" : "nqueen0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "Sample Performance Test (Bogus)",
   "suites" : ["Samples (bogus)"],
   "datfname" : "foo0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
},
{
   "title" : "My Sample Performance Test (Bogus)",
   "suites" : ["Samples (bogus)"],
   "datfname" : "foobar0.json",
   "ylabel" : "Time (seconds)",
   "startdate" : "2026-05-21",
   "enddate" : "2026-05-21",
   "displayrange" : true,
   "defaultexpand" : false,
   "annotations" : []
}
];
var perfSuites = [
{ "suite" : "Release examples" },
{ "suite" : "Performance tracking" },
{ "suite" : "HPC Challenge" },
{ "suite" : "Performance Graphs (TEPS, GB/s, etc.)" },
{ "suite" : "Proxy apps" },
{ "suite" : "Shootout benchmarks" },
{ "suite" : "Submitted Shootout benchmarks" },
{ "suite" : "Shootout extras" },
{ "suite" : "Parboil benchmarks" },
{ "suite" : "PARSEC benchmarks" },
{ "suite" : "ISx benchmark" },
{ "suite" : "PRK benchmarks" },
{ "suite" : "NAS Parallel benchmarks" },
{ "suite" : "Array/Domain performance" },
{ "suite" : "Atomic performance" },
{ "suite" : "Dynamic iterators" },
{ "suite" : "Parallel Statement Comparisons" },
{ "suite" : "Task Spawning" },
{ "suite" : "Barrier" },
{ "suite" : "Memory tracking" },
{ "suite" : "Memory allocation" },
{ "suite" : "Code size tracking" },
{ "suite" : "Startup tracking" },
{ "suite" : "MAX_LOGICAL comparison" },
{ "suite" : "String perf tests" },
{ "suite" : "Standard Library" },
{ "suite" : "Misc" },
{ "suite" : "Colorado State University" },
{ "suite" : "ML" },
{ "suite" : "Nikhil Padmanabhan" },
{ "suite" : "Elegance" },
{ "suite" : "Bale" },
{ "suite" : "Serial Performance" },
{ "suite" : "- Chapel versus C Comparisons" },
{ "suite" : "- Statement Comparisons" },
{ "suite" : "plb2 benchmarks" },
{ "suite" : "Samples (bogus)" }
];
